import type { WorkerDefinition } from "@sdk";

export async function loadBuiltInWorkers(): Promise<WorkerDefinition[]> {
	const [
		{ cleanupDatabaseWorker },
		{ cleanupLogsWorker },
		{ cleanupMetricsWorker },
		{ cleanupOrphanImagesWorker },
		{ cleanupOrphanMediaFilesWorker },
		{ cleanupPluginBlobsWorker },
		{ cleanupTranscodesWorker },
		{ cleanupWorkerHistoryWorker },
		{ imageOptimizationWorker, imageOptimizationScanWorker },
		{ imageProcessingWorker },
		{ libraryErrorsCheckWorker },
		{ libraryScanWorker },
		{ mediaFileAnalysisWorker },
		{ mediaFileAuditWorker, mediaFileAuditReportWorker, mediaMatchAuditScanWorker },
		{ mediaFileIngestWorker },
		{ mediaFileTechnicalRefreshWorker },
		{ mediaFilesRefreshAllWorker },
		{ trickplayGenerateWorker },
		{ downloadsProcessWorker },
		{ metadataRefreshWorker },
		{ streamInitWorker },
	] = await Promise.all([
		import("./definitions/system/cleanup-database.worker"),
		import("./definitions/system/cleanup-logs.worker"),
		import("./definitions/system/cleanup-metrics.worker"),
		import("./definitions/system/cleanup-orphan-images.worker"),
		import("./definitions/system/cleanup-orphan-media-files.worker"),
		import("./definitions/system/cleanup-plugin-blobs.worker"),
		import("./definitions/system/cleanup-transcodes.worker"),
		import("./definitions/system/cleanup-worker-history.worker"),
		import("./definitions/images/image-optimization.worker"),
		import("./definitions/images/image-processing.worker"),
		import("./definitions/libraries/library-errors-check.worker"),
		import("./definitions/libraries/library-scan.worker"),
		import("./definitions/media/media-file-analysis.worker"),
		import("./definitions/media/media-file-audit.worker"),
		import("./definitions/media/media-file-ingest.worker"),
		import("./definitions/media/media-file-technical-refresh.worker"),
		import("./definitions/media/media-files-refresh-all.worker"),
		import("./definitions/media/trickplay-generate.worker"),
		import("./definitions/downloads/downloads-process.worker"),
		import("./definitions/metadata/metadata-refresh.worker"),
		import("./definitions/streaming/stream-initialization.worker"),
	]);

	return [
		imageProcessingWorker,
		imageOptimizationWorker,
		imageOptimizationScanWorker,
		libraryErrorsCheckWorker,
		libraryScanWorker,
		mediaFileAnalysisWorker,
		mediaFileAuditWorker,
		mediaFileAuditReportWorker,
		mediaMatchAuditScanWorker,
		mediaFileIngestWorker,
		mediaFileTechnicalRefreshWorker,
		mediaFilesRefreshAllWorker,
		metadataRefreshWorker,
		streamInitWorker,
		trickplayGenerateWorker,
		downloadsProcessWorker,
		cleanupDatabaseWorker,
		cleanupWorkerHistoryWorker,
		cleanupTranscodesWorker,
		cleanupPluginBlobsWorker,
		cleanupMetricsWorker,
		cleanupOrphanImagesWorker,
		cleanupOrphanMediaFilesWorker,
		cleanupLogsWorker,
	] satisfies WorkerDefinition[];
}
