/**
 * ISO 639-2 (B and T variants) → ISO 639-1. Container tags are three-letter
 * (`eng`, `pol`) while user preferences are two-letter (`en`, `pl`) — without
 * this map the two never match on exact comparison.
 */
const ISO_639_PAIRS: ReadonlyArray<readonly [code: string, code2B: string, code2T?: string]> = [
	["aa", "aar"],
	["ab", "abk"],
	["ae", "ave"],
	["af", "afr"],
	["ak", "aka"],
	["am", "amh"],
	["an", "arg"],
	["ar", "ara"],
	["as", "asm"],
	["av", "ava"],
	["ay", "aym"],
	["az", "aze"],
	["ba", "bak"],
	["be", "bel"],
	["bg", "bul"],
	["bh", "bih"],
	["bi", "bis"],
	["bm", "bam"],
	["bn", "ben"],
	["bo", "bod", "tib"],
	["br", "bre"],
	["bs", "bos"],
	["ca", "cat"],
	["ce", "che"],
	["ch", "cha"],
	["co", "cos"],
	["cr", "cre"],
	["cs", "ces", "cze"],
	["cu", "chu"],
	["cv", "chv"],
	["cy", "cym", "wel"],
	["da", "dan"],
	["de", "deu", "ger"],
	["dv", "div"],
	["dz", "dzo"],
	["ee", "ewe"],
	["el", "ell", "gre"],
	["en", "eng"],
	["eo", "epo"],
	["es", "spa"],
	["et", "est"],
	["eu", "eus", "baq"],
	["fa", "fas", "per"],
	["ff", "ful"],
	["fi", "fin"],
	["fj", "fij"],
	["fo", "fao"],
	["fr", "fra", "fre"],
	["fy", "fry"],
	["ga", "gle"],
	["gd", "gla"],
	["gl", "glg"],
	["gn", "grn"],
	["gu", "guj"],
	["gv", "glv"],
	["ha", "hau"],
	["he", "heb"],
	["hi", "hin"],
	["ho", "hmo"],
	["hr", "hrv"],
	["ht", "hat"],
	["hu", "hun"],
	["hy", "hye", "arm"],
	["hz", "her"],
	["ia", "ina"],
	["id", "ind"],
	["ie", "ile"],
	["ig", "ibo"],
	["ii", "iii"],
	["ik", "ipk"],
	["io", "ido"],
	["is", "isl", "ice"],
	["it", "ita"],
	["iu", "iku"],
	["ja", "jpn"],
	["jv", "jav"],
	["ka", "kat", "geo"],
	["kg", "kon"],
	["ki", "kik"],
	["kj", "kua"],
	["kk", "kaz"],
	["kl", "kal"],
	["km", "khm"],
	["kn", "kan"],
	["ko", "kor"],
	["kr", "kau"],
	["ks", "kas"],
	["ku", "kur"],
	["kv", "kom"],
	["kw", "cor"],
	["ky", "kir"],
	["la", "lat"],
	["lb", "ltz"],
	["lg", "lug"],
	["li", "lim"],
	["ln", "lin"],
	["lo", "lao"],
	["lt", "lit"],
	["lu", "lub"],
	["lv", "lav"],
	["mg", "mlg"],
	["mh", "mah"],
	["mi", "mri", "mao"],
	["mk", "mkd", "mac"],
	["ml", "mal"],
	["mn", "mon"],
	["mr", "mar"],
	["ms", "msa", "may"],
	["mt", "mlt"],
	["my", "mya", "bur"],
	["na", "nau"],
	["nb", "nob"],
	["nd", "nde"],
	["ne", "nep"],
	["ng", "ndo"],
	["nl", "nld", "dut"],
	["nn", "nno"],
	["no", "nor"],
	["nr", "nbl"],
	["nv", "nav"],
	["ny", "nya"],
	["oc", "oci"],
	["oj", "oji"],
	["om", "orm"],
	["os", "oss"],
	["pa", "pan"],
	["pi", "pli"],
	["pl", "pol"],
	["ps", "pus"],
	["pt", "por"],
	["qu", "que"],
	["rm", "roh"],
	["rn", "run"],
	["ro", "ron", "rum"],
	["ru", "rus"],
	["rw", "kin"],
	["sa", "san"],
	["sc", "srd"],
	["sd", "snd"],
	["se", "sme"],
	["sg", "sag"],
	["si", "sin"],
	["sk", "slk", "slo"],
	["sl", "slv"],
	["sm", "smo"],
	["sn", "sna"],
	["so", "som"],
	["sq", "sqi", "alb"],
	["sr", "srp"],
	["ss", "ssw"],
	["st", "sot"],
	["su", "sun"],
	["sv", "swe"],
	["sw", "swa"],
	["ta", "tam"],
	["te", "tel"],
	["tg", "tgk"],
	["th", "tha"],
	["ti", "tir"],
	["tk", "tuk"],
	["tl", "tgl"],
	["tn", "tsn"],
	["to", "ton"],
	["tr", "tur"],
	["ts", "tso"],
	["tt", "tat"],
	["tw", "twi"],
	["ty", "tah"],
	["ug", "uig"],
	["uk", "ukr"],
	["ur", "urd"],
	["uz", "uzb"],
	["ve", "ven"],
	["vi", "vie"],
	["vo", "vol"],
	["wa", "wln"],
	["wo", "wol"],
	["xh", "xho"],
	["yi", "yid"],
	["yo", "yor"],
	["za", "zha"],
	["zh", "zho", "chi"],
	["zu", "zul"],
];

const ISO_639_2_TO_639_1 = new Map<string, string>(
	ISO_639_PAIRS.flatMap(
		([code, code2B, code2T]): Array<[string, string]> =>
			code2T
				? [
						[code2B, code],
						[code2T, code],
					]
				: [[code2B, code]],
	),
);

/** Maps an ISO 639-2 language code to its ISO 639-1 equivalent; other values pass through unchanged. */
export function toIso639_1(language: string): string {
	return ISO_639_2_TO_639_1.get(language) ?? language;
}
