import {
	LoginResponseSchema,
	QuickConnectAuthorizeRequestSchema,
	QuickConnectCheckResponseSchema,
	QuickConnectGenerateResponseSchema,
	QuickConnectInitiateResponseSchema,
	QuickConnectRedeemRequestSchema,
} from "@reelvault/sdk/common";
import { Elysia, t } from "elysia";
import { commonModel, ROUTE_ERRORS } from "@/api/schemas/common.schemas";
import { quickConnectService } from "@/application/auth/quick-connect.service";
import { authMiddleware } from "@/middleware/auth.middleware";
import { rateLimitMiddleware } from "@/middleware/rate-limit.middleware";
import { MINUTE } from "@/server.constants";
import { UnauthorizedError } from "@/utils/errors";

export const quickConnectRoutes = new Elysia({
	prefix: "/quick-connect",
	tags: ["Auth"],
})
	.use(commonModel)
	.use(rateLimitMiddleware)
	.model({
		"quickConnect.initiate.response": QuickConnectInitiateResponseSchema,
		"quickConnect.check.response": QuickConnectCheckResponseSchema,
		"quickConnect.authorize.body": QuickConnectAuthorizeRequestSchema,
		"quickConnect.generate.response": QuickConnectGenerateResponseSchema,
		"quickConnect.redeem.body": QuickConnectRedeemRequestSchema,
		"quickConnect.redeem.response": LoginResponseSchema,
	})
	.post("/initiate", async () => await quickConnectService.initiate(), {
		response: {
			200: "quickConnect.initiate.response",
			500: "error.response",
		},
		rateLimit: { name: "qc-initiate", max: 10, windowMs: MINUTE },
		detail: {
			description: "Initiate TV/device pairing by generating a quick connect code and secret.",
		},
	})
	.post("/check", async ({ body, request }) => await quickConnectService.check(body.secret, request), {
		// Secret moved out of the URL query so it never lands in proxy/access logs
		// or browser history (polling via POST every 2.5 s is fine).
		body: t.Object({ secret: t.String({ minLength: 1 }) }),
		response: {
			200: "quickConnect.check.response",
			404: "error.response",
			500: "error.response",
		},
		rateLimit: { name: "qc-check", max: 60, windowMs: MINUTE },
		detail: {
			description: "Check if the initiated quick connect code has been authorized.",
		},
	})
	.post("/redeem", async ({ body, request }) => await quickConnectService.redeem(body.code, request), {
		body: "quickConnect.redeem.body",
		response: {
			200: "quickConnect.redeem.response",
			400: "error.response",
			404: "error.response",
			500: "error.response",
		},
		rateLimit: { name: "qc-redeem", max: 5, windowMs: MINUTE },
		detail: {
			description: "Redeem a quick login voucher code generated by an account or profile.",
		},
	})
	.use(authMiddleware)
	.post(
		"/authorize",
		async ({ body, user, profile }) => {
			if (!user) throw new UnauthorizedError("Unauthorized");

			return await quickConnectService.authorize(body.code, user, profile);
		},
		{
			auth: true,
			body: "quickConnect.authorize.body",
			response: { 200: "success.response", ...ROUTE_ERRORS.VALIDATED_NOT_FOUND, 500: "error.response" },
			rateLimit: { name: "qc-authorize", max: 10, windowMs: MINUTE },
			detail: {
				description: "Authorize a pending device quick connect code using current authenticated user/profile.",
			},
		},
	)
	.post(
		"/generate",
		async ({ user, profile }) => {
			if (!user) throw new UnauthorizedError("Unauthorized");

			return await quickConnectService.generate(user, profile);
		},
		{
			auth: true,
			response: { 200: "quickConnect.generate.response", ...ROUTE_ERRORS.AUTH, 500: "error.response" },
			rateLimit: { name: "qc-generate", max: 10, windowMs: MINUTE },
			detail: {
				description: "Generate a quick login voucher code for this user and profile.",
			},
		},
	);
